// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

export function ChooseDirectory(current: string): $CancellablePromise<string> {
    return $Call.ByID(2271257277, current);
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(717304023);
}

export function ExportLogs(filter: app$0.LogFilterDTO): $CancellablePromise<string> {
    return $Call.ByID(2943527410, filter);
}

export function GetLogs(filter: app$0.LogFilterDTO): $CancellablePromise<app$0.LogEntryDTO[]> {
    return $Call.ByID(4012054750, filter).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStatus(): $CancellablePromise<app$0.StatusDTO> {
    return $Call.ByID(3149098951).then(($result: any) => {
        return $$createType2($result);
    });
}

export function OpenConfigDir(): $CancellablePromise<void> {
    return $Call.ByID(644463484);
}

export function SetCredentials(patch: app$0.CredentialPatchDTO): $CancellablePromise<app$0.StatusDTO> {
    return $Call.ByID(306194325, patch).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StartSharing(): $CancellablePromise<app$0.StatusDTO> {
    return $Call.ByID(3556961239).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StopSharing(): $CancellablePromise<app$0.StatusDTO> {
    return $Call.ByID(2713997397).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateConfig(patch: app$0.ConfigPatchDTO): $CancellablePromise<app$0.StatusDTO> {
    return $Call.ByID(2775678876, patch).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = app$0.LogEntryDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = app$0.StatusDTO.createFrom;
