// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class ConfigDTO {
    "rootPath": string;
    "port": number;
    "maxLevel": number;
    "isAllowUpload": boolean;
    "isSecure": boolean;
    "scratchMaxItems": number;
    "scratchMaxItemSize": string;

    /** Creates a new ConfigDTO instance. */
    constructor($$source: Partial<ConfigDTO> = {}) {
        if (!("rootPath" in $$source)) {
            this["rootPath"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("maxLevel" in $$source)) {
            this["maxLevel"] = 0;
        }
        if (!("isAllowUpload" in $$source)) {
            this["isAllowUpload"] = false;
        }
        if (!("isSecure" in $$source)) {
            this["isSecure"] = false;
        }
        if (!("scratchMaxItems" in $$source)) {
            this["scratchMaxItems"] = 0;
        }
        if (!("scratchMaxItemSize" in $$source)) {
            this["scratchMaxItemSize"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigDTO($$parsedSource as Partial<ConfigDTO>);
    }
}

export class ConfigPatchDTO {
    "rootPath"?: string | null;
    "port"?: number | null;
    "maxLevel"?: number | null;
    "isAllowUpload"?: boolean | null;
    "isSecure"?: boolean | null;
    "scratchMaxItems"?: number | null;
    "scratchMaxItemSize"?: string | null;
    "restartPort"?: boolean;

    /** Creates a new ConfigPatchDTO instance. */
    constructor($$source: Partial<ConfigPatchDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigPatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigPatchDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigPatchDTO($$parsedSource as Partial<ConfigPatchDTO>);
    }
}

export class CredentialPatchDTO {
    "username": string;
    "password": string;
    "confirmPassword": string;
    "enableSecure": boolean;

    /** Creates a new CredentialPatchDTO instance. */
    constructor($$source: Partial<CredentialPatchDTO> = {}) {
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("confirmPassword" in $$source)) {
            this["confirmPassword"] = "";
        }
        if (!("enableSecure" in $$source)) {
            this["enableSecure"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialPatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialPatchDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialPatchDTO($$parsedSource as Partial<CredentialPatchDTO>);
    }
}

export class LogEntryDTO {
    "time": time$0.Time;
    "clientIP": string;
    "method": string;
    "event": string;
    "path": string;
    "status": number;
    "result": string;

    /** Creates a new LogEntryDTO instance. */
    constructor($$source: Partial<LogEntryDTO> = {}) {
        if (!("time" in $$source)) {
            this["time"] = null;
        }
        if (!("clientIP" in $$source)) {
            this["clientIP"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("event" in $$source)) {
            this["event"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryDTO($$parsedSource as Partial<LogEntryDTO>);
    }
}

export class LogFilterDTO {
    "event"?: string;
    "since"?: time$0.Time | null;
    "until"?: time$0.Time | null;

    /** Creates a new LogFilterDTO instance. */
    constructor($$source: Partial<LogFilterDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFilterDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFilterDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFilterDTO($$parsedSource as Partial<LogFilterDTO>);
    }
}

export class StatusDTO {
    "running": boolean;
    "stateLabel": string;
    "address": string;
    "config": ConfigDTO;
    "hasCredentials": boolean;
    "configPath": string;
    "accessLogPath": string;
    "portRestartRequired": boolean;
    "lastError": string;

    /** Creates a new StatusDTO instance. */
    constructor($$source: Partial<StatusDTO> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("stateLabel" in $$source)) {
            this["stateLabel"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new ConfigDTO());
        }
        if (!("hasCredentials" in $$source)) {
            this["hasCredentials"] = false;
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("accessLogPath" in $$source)) {
            this["accessLogPath"] = "";
        }
        if (!("portRestartRequired" in $$source)) {
            this["portRestartRequired"] = false;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusDTO {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField3_0($$parsedSource["config"]);
        }
        return new StatusDTO($$parsedSource as Partial<StatusDTO>);
    }
}

// Private type creation functions
const $$createType0 = ConfigDTO.createFrom;
